### ISSUE TITLE
How to activate a scene tutorial bug

### ISSUE THREAD

**Issue by lhuxohl** [openbase/bco.dal#150]
Wait for execution at the end of the tutorial does not return. Even though the action is correctly executed.

**Comment by DivineThreepwood** [comment]
Bug was caused by the scene configuration. Within the party scene the tile follower light animation app is active which for sure continuously changes the color of all lights. Additionally, the scene included initial light color actions, but those actions were never executed since the tile follower app executes the tasks with a higher priority. 

The initial light color actions are removed which should solve the issue after updating the demo db.

tutorial needs still be tested again.

**Comment by DivineThreepwood** [comment]
@lhuxohl Can you test the fix and validate if the howto is running like expected?

**Comment by lhuxohl** [comment]
Tested the fix. Everything seems to work fine now.

**Comment by DivineThreepwood** [comment]
Thanks!
