### ISSUE TITLE
ServiceRemoteManager does not include unit subtypes during filtered controlling.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#68]
The call ```locationRemote.setPowerState(PowerState.State.ON, UnitType.COLORABLE_LIGHT);``` only effects Lights but totally ignores ColorableLights.

Please include unit subtypes as well.

**Comment by pLeminoq** [comment]
In what context did this not work? I just tried this in hardware simulation mode and all ColorableLights are triggered as well.
Additionally I had a look at the code and the ServiceRemoteManager does not care about unit types at all. It just looks at the services a unit offers and since ColorableLights have a PowerStateService they should not be excluded.

**Comment by pLeminoq** [comment]
Sorry I overlooked filtering by unit type. And the filtering indeed did not include sub types. This has been fixed in commit 9e02b04d21bf4703d1adbc82e3f56585f52839cd.
