### ISSUE TITLE
launcher exclution does not work anymore

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#98]
e.g.
<pre>bco-openhab --exclude-launcher app-manager</pre>
does not exlucde the app-manager anymore.

**Comment by pLeminoq** [comment]
The launcher exclusion still works. The issue is that you added the minus in 'app-manager'. The test for exclusion is as follows:

<pre>
if (launcherEntry.getKey().getName().toLowerCase().contains(exclusionPatter.toLowerCase())) {
    exclude = true;
}
</pre>

where launcherEntry.getKey() is the launcher class. For the app manager this is AppManagerLauncher. So if your commando should work maybe the test has to be adapted to exclude the minus.
Otherwise I would suggest to use:

<pre>
bco --print-launcher
</pre>

to get the names of all launcher that can be excluded.

**Comment by pLeminoq** [comment]
Minuses and underscores are ignored for this check since commit openbase/jul@029a30e5a5a1057344d654c6193df13a6a7790c2
